language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

  - go get -v -d -t ./...

script:
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
